### ISSUE TITLE
Are you using RPLIDAR A2?

### ISSUE THREAD

**Issue by jabrena** [carlemil/RPLidarA2AndroidThingsAPI#1]
Hi,

Today, I discovered your project and I would like to know if you are using for the project, RPLIDAR A1 or A2?

Many thanks in advance.

Juan Antonio

**Comment by carlemil** [comment]
Im using a A2 but the changes for a A1 should not be huge since its mostly a expansion on that api from what i understand. I just started working on it and will not have anything ready for another few weeks. If you want to contribute just make a pull request :D

**Comment by jabrena** [comment]
Hi @carlemil,

Tomorrow, I will isolate the library about the sensor to test it on a RaspberryPi.

Cheers

**Comment by jabrena** [comment]
I was checking the serial dependency and unfortunately, I will not able to test on the target device.
It is a pity. The code would seem clean.

https://github.com/felHR85/UsbSerial/blob/master/usbserial/src/main/java/com/felhr/usbserial/UsbSpiDevice.java

Cheers

**Comment by carlemil** [comment]
Why did it not work? Something i can do to help perhaps?
